### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by fahrertuer** [buddycloud/buddycloud-pusher#13]
My email inbox is receiving a more or less steady flow of notification emails
To be a bit more precise: New follower notifications - for channels I don't own (like dodo's personal channel or the lounge)
Problem with the pusher I assume

**Comment by abmargb** [comment]
Are you moderator of the channel, maybe?

On Sun, Sep 29, 2013 at 2:47 PM, fahrertuer notifications@github.comwrote:

> My email inbox is receiving a more or less steady flow of notification
> emails
> To be a bit more precise: New follower notifications - for channels I
> don't own (like dodo's personal channel or the lounge)
> Problem with the pusher I assume
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/buddycloud/buddycloud-pusher/issues/13
> .

## 

Abmar Barros
MSc in Computer Science from the Federal University of Campina Grande -
www.ufcg.edu.br
OurGrid Team Leader - www.ourgrid.org
Buddycloud Dev - www.buddycloud.org
Paraíba - Brazil

**Comment by abmargb** [comment]
Removing weird owner affiliations from the channel server DB seems to have fixed this.
