### ISSUE TITLE
Lots of PSQLException: FATAL: terminating connection due to administrator command

### ISSUE THREAD

**Issue by abmargb** [buddycloud/buddycloud-pusher#2]
SIGTERM coming from administrative software might bt the reason

http://postgresql.1045698.n5.nabble.com/Getting-FATAL-terminating-connection-due-to-administrator-command-td2840596.html

Majority of the traces are from last month, so the recent server upgrade might have solved this. We need to check it anyway.

**Comment by abmargb** [comment]
Setting limits in the connection pool library (c3p0) configuration seems to have solved this.

**Comment by msolnit** [comment]
@abmargb: I happened upon this thread via a Google search.  I'm actually having the exact same issue.  Could you describe in more detail which c3p0 settings you changed?  Sorry to hijack GitHub for this purpose :-).

**Comment by abmargb** [comment]
@msolnit  https://github.com/buddycloud/channel-directory/blob/master/src/main/java/com/buddycloud/channeldirectory/commons/db/ChannelDirectoryDataSource.java#L77 Is this what you are looking for?

**Comment by msolnit** [comment]
@abmargb: Thanks for your quick response!  If that's the only change you made, then yes, it's what I'm looking for :-).  I'll try it out.
