### ISSUE TITLE
Missing Mail notifications

### ISSUE THREAD

**Issue by Schnouki** [buddycloud/buddycloud-pusher#9]
(Moved from [server issue #104](https://github.com/buddycloud/buddycloud-server/issues/104) by @fahrertuer)

Since we have not just email notifications but also in client notifications I have discovered a huge discrepancy between both.

I assume this is a server issue, since the problems I see are with email notifications, which I assume to be part of the server and not of the webclient. If it is part of the webclient: please move this or notify me to open an issue there

So, the problem is:
I have activated all possible email notifications in the preferences page
But I only seem to get email notifications for two channels: simon@buddycloud.org and team@channels.buddycloud.org
For no other channel was there an email notification in my inbox despite heavy posting in some channels

**Comment by abmargb** [comment]
@Schnouki are you still experiencing this?

**Comment by fahrertuer** [comment]
Since I was the original poster of the issue before it was moved I'll answer:
Nope. This seems to be gone, or at least so sporadic that I don't recognize it happening

**Comment by abmargb** [comment]
Thanks @fahrertuer. I'm closing it.
